print("1. Remove any items from the bed (pillows, blankets, etc.).")
print("2. Straighten the fitted sheet on the mattress.")
print("3. Spread the flat sheet evenly over the bed.")
print("4. Tuck the flat sheet under the mattress at the foot of the bed.")
print("5. Spread the blanket or comforter evenly over the bed.")
print("6. Place pillows at the head of the bed.")
print("Bed is made.")
