# 1. Import the datetime module.
# 2. Use the datetime.now class from the datetime module to calculate the  current time.
# 3. Display the value generated by datetime.datetime.now().
# 17.5 What time is it now?
import datetime
time_now = datetime.datetime.now()
print(time_now)